
x-common-env: &env_constants
  PHONEBOOK_FRONTEND_NODE_IMAGE: ${PHONEBOOK_FRONTEND_NODE_IMAGE:-16.14.2-alpine3.15}
  PHONEBOOK_FRONTEND_NGINX_IMAGE: ${PHONEBOOK_FRONTEND_NGINX_IMAGE:-1.21.6-alpine}
  PHONEBOOK_BACKEND_NODE_IMAGE: ${PHONEBOOK_BACKEND_NODE_IMAGE:-16.14.2-alpine3.15}
  PHONEBOOK_BACKEND_URL: ${PHONEBOOK_BACKEND_URL:-/api/}


services:

  nginx:
    image: nginx:${PHONEBOOK_REVERSE_PROXY_NGINX_IMAGE:-1.21.6-alpine}
    volumes:
      - ./nginx.reverse-proxy.conf:/etc/nginx/nginx.conf:ro
    ports:
      - ${PHONEBOOK_REVERSE_PROXY_PORT:-8080}:80
    networks:
      - phonebook
    container_name: phonebook-prod-reverse-proxy
    depends_on:
      - frontend

  frontend:
    image: phonebook-prod-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        <<: *env_constants
    networks:
      - phonebook
    container_name: phonebook-prod-frontend
    depends_on:
      - backend

  backend:
    image: phonebook-prod-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        <<: *env_constants
    volumes:
      - db:/usr/src/app/data
    networks:
      - phonebook
    container_name: phonebook-prod-backend


networks:
  phonebook:
    name: phonebook-prod

volumes:
  db:
    name: phonebook-prod-db
