
x-common-env: &env_constants
  PHONEBOOK_FRONTEND_NODE_IMAGE: ${PHONEBOOK_FRONTEND_NODE_IMAGE:-16.14.2-alpine3.15}
  PHONEBOOK_BACKEND_NODE_IMAGE: ${PHONEBOOK_BACKEND_NODE_IMAGE:-16.14.2-alpine3.15}
  PHONEBOOK_BACKEND_URL: ${PHONEBOOK_BACKEND_URL:-http://localhost:3001/}


services:

  nginx:
    image: nginx:${PHONEBOOK_NGINX_IMAGE:-1.21.6-alpine}
    volumes:
      - ./nginx.reverse-proxy.conf:/etc/nginx/nginx.conf:ro
    ports:
      - ${PHONEBOOK_REV_PROXY_PORT:-8080}:80
    networks:
      - phonebook
    container_name: phonebook-dev-reverse-proxy
    depends_on:
      - frontend

  frontend:
    image: phonebook-dev-frontend
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
      args:
        <<: *env_constants
    volumes:
      - ./frontend/:/usr/src/app
    ports:
      - ${PHONEBOOK_FRONTEND_DEV_PORT:-3000}:3000
    networks:
      - phonebook
    container_name: phonebook-dev-frontend
    depends_on:
      - backend

  backend:
    image: phonebook-dev-backend
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
      args:
        <<: *env_constants
    volumes:
      - ./backend/:/usr/src/app
      - db:/usr/src/app/data
    ports:
      - ${PHONEBOOK_BACKEND_DEV_PORT:-3001}:3000
    networks:
      - phonebook
    container_name: phonebook-dev-backend


networks:
  phonebook:
    name: phonebook-dev

volumes:
  db:
    name: phonebook-dev-db
