
services:

  nginx:
    image: nginx:1.21.6
    volumes:
      - ./nginx.reverse-proxy.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: todo-prod-reverse-proxy
    depends_on:
      - frontend

  frontend:
    image: todo-prod-frontend
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
      args:
        - BACKEND_URL=/api/
    volumes:
      - ./todo-frontend/:/usr/src/app

    container_name: todo-prod-frontend
    depends_on:
      - backend

  backend:
    image: todo-prod-backend
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    volumes:
      - ./todo-backend/:/usr/src/app
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - REDIS_URL=redis://redis:6379/
    container_name: todo-prod-backend
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:5.0.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data/:/data/db
    container_name: todo-prod-db-mongo

  redis:
    image: redis:6.2.6
    volumes:
      - ./todo-backend/redis_data/:/data
    container_name: todo-prod-db-redis
