
version: '3.8'

services:
  mongo:
    image: mongo:5.0.6
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongo_data:/data/db
    container_name: todo-dev-db-mongo
  redis:
    image: redis:6.2.6
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data
    container_name: todo-dev-db-redis
  backend:
    image: todo-backend-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 3001:3000
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - REDIS_URL=redis://redis:6379/
    container_name: todo-dev-backend
